version: '3.9'
services:
  web:
    build: ./my-react-docker
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - api
    # networks:
    #   - app-network
      
  api:
    build: ./my-express-docker
    ports:
      - 3001:3001
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge